# Generated by Django 4.2.7 on 2025-11-20 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Kode SKU')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Barang')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Barang')),
                ('satuan', models.CharField(max_length=20, verbose_name='Satuan (pcs/kg/liter)')),
                ('gambar_url', models.URLField(blank=True, verbose_name='URL Gambar Barang')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Gudang')),
                ('lokasi', models.CharField(max_length=200, verbose_name='Lokasi Gudang')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Gudang')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Kategori')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Supplier')),
                ('kontak', models.CharField(blank=True, max_length=100, verbose_name='Nama Kontak')),
                ('telepon', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(verbose_name='Jumlah Stok')),
                ('level_reorder', models.PositiveIntegerField(default=10, verbose_name='Level Reorder (Minimal Stok)')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='inventaris.barang', verbose_name='Barang')),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='inventaris.gudang', verbose_name='Gudang')),
            ],
            options={
                'unique_together': {('barang', 'gudang')},
            },
        ),
        migrations.CreateModel(
            name='RiwayatStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('IN', 'Masuk'), ('OUT', 'Keluar')], max_length=3, verbose_name='Tipe Pergerakan')),
                ('jumlah', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan (contoh: Pengiriman ke toko)')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='inventaris.stok', verbose_name='Stok')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='inventaris.kategori', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='barang',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barang', to='inventaris.supplier', verbose_name='Supplier'),
        ),
    ]
