# Generated by Django 4.2.7 on 2025-11-22 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatstok',
            name='catatan',
            field=models.TextField(blank=True, verbose_name='Catatan Pergerakan'),
        ),
        migrations.AlterField(
            model_name='riwayatstok',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Petugas'),
        ),
        migrations.AlterField(
            model_name='riwayatstok',
            name='jumlah',
            field=models.PositiveIntegerField(verbose_name='Jumlah Barang'),
        ),
        migrations.AlterField(
            model_name='riwayatstok',
            name='stok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='inventaris.stok', verbose_name='Stok Barang'),
        ),
    ]
