# Generated by Django 4.2.7 on 2025-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_alter_riwayatstok_catatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='gambar_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL Gambar Barang'),
        ),
    ]
